# mysql connect configuration
mysql:
    username: root
    password: '123456'
    path: '127.0.0.1:3306'
    db-name: 'hyperf'
    config: 'charset=utf8&parseTime=True&loc=Local'
    max-idle-conns: 10
    max-open-conns: 10
    log-mode: true

# logger configuration
log:
    prefix: '[Hello_GIN]'
    log-file: true
    stdout: 'DEBUG'
    file: 'DEBUG'
